/**
 * dev.routes.js — DEV-ONLY endpoints. Never mount in production.
 *
 * POST /dev/test-email
 *   Sends a test email through the configured SMTP (Mailpit in dev)
 *   so you can verify the mailer config end-to-end without triggering
 *   a real auth flow.
 *
 * Body (all optional):
 *   { to, subject, message }
 */

const express = require("express");
const { sendPasswordResetEmail, verifyMailConfig } = require("../utils/mailer");
const nodemailer = require("nodemailer");
const env = require("../config/env");

const router = express.Router();

// ── POST /dev/test-email ───────────────────────────────────────────────────────
router.get("/test-email", async (req, res) => {
  const {
    to      = "test@vylapp.dev",
    subject = "📬 Vylapp — SMTP Test",
    message = "If you can read this, your Mailpit + nodemailer setup is working perfectly! 🎉",
  } = req.query;

  try {
    // 1. Verify the SMTP connection first
    const smtpOk = await verifyMailConfig();

    // 2. Build a simple transporter inline so this route is self-contained
    //    and doesn't depend on state from other modules.
    const transporter = nodemailer.createTransport({
      host: env.mailHost,
      port: env.mailPort,
      secure: env.mailScheme === "ssl",
    });

    // 3. Send the test email
    const info = await transporter.sendMail({
      from:    `"Vylapp Dev" <dev@vylapp.dev>`,
      to,
      subject,
      text: message,
      html: `
        <div style="font-family:'Inter',system-ui,sans-serif;background:#f9fafb;padding:40px 20px;text-align:center;">
          <div style="max-width:480px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;
                      box-shadow:0 4px 6px -1px rgba(0,0,0,.1);border:1px solid #f3f4f6;">
            <div style="background:linear-gradient(135deg,#7C3AED 0%,#C084FC 100%);padding:28px;color:#fff;">
              <h1 style="margin:0;font-size:22px;font-weight:800;">Vylapp</h1>
              <p  style="margin:4px 0 0;font-size:13px;opacity:.85;">Developer Email Test</p>
            </div>
            <div style="padding:32px 28px;text-align:left;color:#1f2937;line-height:1.65;">
              <h2 style="margin:0 0 12px;font-size:18px;font-weight:700;color:#111827;">📬 SMTP is working!</h2>
              <p  style="margin:0 0 20px;font-size:15px;">${message}</p>
              <table style="width:100%;border-collapse:collapse;font-size:13px;color:#6b7280;">
                <tr>
                  <td style="padding:6px 0;font-weight:600;color:#374151;width:120px;">SMTP Host</td>
                  <td style="padding:6px 0;">${env.mailHost}:${env.mailPort}</td>
                </tr>
                <tr>
                  <td style="padding:6px 0;font-weight:600;color:#374151;">To</td>
                  <td style="padding:6px 0;">${to}</td>
                </tr>
                <tr>
                  <td style="padding:6px 0;font-weight:600;color:#374151;">Sent at</td>
                  <td style="padding:6px 0;">${new Date().toISOString()}</td>
                </tr>
              </table>
            </div>
            <div style="background:#f9fafb;padding:16px;text-align:center;font-size:12px;color:#9ca3af;border-top:1px solid #f3f4f6;">
              This email was generated by the <strong>/dev/test-email</strong> endpoint — dev only.
            </div>
          </div>
        </div>
      `,
    });

    return res.json({
      ok:          true,
      smtp_verify: smtpOk,
      message_id:  info.messageId,
      accepted:    info.accepted,
      rejected:    info.rejected,
      mailpit_ui:  "http://localhost:8026",
      sent_to:     to,
      subject,
    });
  } catch (err) {
    console.error("[dev/test-email] Error:", err);
    return res.status(500).json({
      ok:    false,
      error: err.message,
      hint:  "Check that Mailpit is running and MAIL_HOST/MAIL_PORT are correct in backend/.env",
    });
  }
});

// ── POST /dev/test-reset-email ────────────────────────────────────────────────
// Fires the real password-reset template so you can preview it in Mailpit.
router.post("/test-reset-email", async (req, res) => {
  const {
    to          = "user@vylapp.dev",
    displayName = "Test Viber",
    token       = "dev-fake-reset-token-abc123",
  } = req.body;

  try {
    const info = await sendPasswordResetEmail(to, token, displayName);
    return res.json({
      ok:         true,
      message_id: info.messageId,
      accepted:   info.accepted,
      mailpit_ui: "http://localhost:8026",
      sent_to:    to,
      reset_link: `${env.clientOrigin}/reset-password?token=${token}`,
    });
  } catch (err) {
    console.error("[dev/test-reset-email] Error:", err);
    return res.status(500).json({ ok: false, error: err.message });
  }
});

module.exports = router;
